version: '3.8'
services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: VE9QMTBPV0FTUA==
      MYSQL_DATABASE: owasp
      MYSQL_USER: hacker
      MYSQL_PASSWORD: aW50cnVkZXI=
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
